name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Torrent file URL"
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: inputs.maximize_disk_space
        uses: easimon/maximize-build-space@v6
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Free Space
        run: df -h

      - name: Fixed permission
        run: sudo chown -R $USER /data

      - name: Rclone setup
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Dowload FIle
        run: npx webtorrent-cli "${{ github.event.inputs.url }}" -o /data

      - name: Copy file to Drive
        run:  "rclone copy /data/ gdrive:bot/ --ignore-existing -P --checkers 32 --transfers 16 --retries 6  --low-level-retries 10 --fast-list --drive-chunk-size 512M --tpslimit 10 --retries-sleep 2m --drive-upload-cutoff 1000T --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36'"
