name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    steps:

        - name: Maximize disk space
          if: inputs.maximize_disk_space
          uses: easimon/maximize-build-space@v6
          with:
            remove-dotnet: true
            remove-android: true
            remove-haskell: true
        
       
        - name: Write .env File
          run: |
              echo '${{ secrets.DOTENV }}' >> .env
          
        - name: Dowload File
          run: npx webtorrent-cli "${{ github.event.inputs.url }}" -o /data  
      
        - name: LS
          run: cd /data && ls -la
