name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    
#         - name: current shell and user
#           run: echo $SHELL && whoami
    
#         - name: Maximize disk space
#           if: inputs.maximize_disk_space
#           uses: easimon/maximize-build-space@v6
#           with:
#             remove-dotnet: true
#             remove-android: true
#             remove-haskell: true
        
          
        - name: Fixed permission
          run: sudo chown -R $USER /data
          
          
        - name: Rclone setup
          uses: AnimMouse/setup-rclone@v1
          with:
            rclone_config: ${{ secrets.RCLONE_CONFIG }}
            
        - name: list rclone drive
          run: 'rclone config'

#         - name: Dowload FIle
#           run: npx webtorrent-cli "${{ github.event.inputs.url }}" -o /data  
      
          


