name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    


        - name: Maximize disk space
          if: inputs.maximize_disk_space
          uses: easimon/maximize-build-space@v6
          with:
            remove-dotnet: true
            remove-android: true
            remove-haskell: true
        
       
        - name: Write .env File
          run: |
              echo '${{ secrets.DOTENV }}' >> .env
          
        - name: Fixed permission
          run: sudo chown -R $USER /data
          
        - name: Dowload FIle
          run: npx webtorrent-cli "${{ github.event.inputs.url }}" -o /data  
      
        - name: LS
          run: cd /data && ls -la
          
        - name: Current dir
          run: pwd
          
        - name: Install rclone dependicies 
          run: sudo apt install -y bash curl unzip ca-certificates fuse openssh-client
          
        - name: Install rclone 
          run: wget -qO- https://rclone.org/install.sh | bash
            
        - name: make rclone config foler
          run: mkdir ~/.config/rclone
          
        - name: copy rclone config
          run: echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          
        - name: Check config file
          run: cat ~/.config/rclone/rclone.conf

