name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
       
        - name: Write .env File
          run: |
              echo '${{ secrets.DOTENV }}' >> .env
        
        - name: Install aria2
          run: apt install -y transmission-cli 
          
        - name: Dowload File
          run: transmission-cli "${{ github.event.inputs.url }}" -w /data
      
        - name: LS
          run: cd /data && ls -la
          
        - name: Upload to Drive
          run: node /app/upload.js
